{'acqiris': {'desc': 'CXI Acqiris',
             'det': {'detId': 0,
                     'detName': 'CxiEndstation',
                     'devId': 0,
                     'devName': 'Acqiris'},
             'device': 'acqiris'},
 'atc': {'desc': 'CXI DSB Attenuators',
         'device': 'attn',
         'pvs': {'a0': 'CXI:ATC:MMS:26',
                 'a1': 'CXI:ATC:MMS:25',
                 'a2': 'CXI:ATC:MMS:24',
                 'a3': 'CXI:ATC:MMS:23',
                 'a4': 'CXI:ATC:MMS:22',
                 'a5': 'CXI:ATC:MMS:21'}},
 'dg1pim': {'desc': 'CXI DG1 pop-in camera',
            'det': {'detId': 0,
                    'detName': 'CxiDg1',
                    'devId': 0,
                    'devName': 'TM6740'},
            'device': 'pim',
            'pvs': {'y': 'CXI:DG1:MMS:08', 'zoom': 'CXI:DG1:CLZ:01'}},
 'dg1slit': {'desc': 'CXI DG1 slits',
             'device': 'slit',
             'pvs': {'xm': 'CXI:DG1:MMS:07', 'xp': 'CXI:DG1:MMS:06'}},
 'dg2diode': {'desc': 'CXI DG2 diode assembly',
              'det': {'detId': 0,
                      'detName': 'CxiDg2',
                      'devId': 0,
                      'devName': 'Ipimb'},
              'device': 'diode',
              'pvs': {'targ': 'CXI:DG2:MMS:09',
                      'x': 'CXI:DG2:MMS:07',
                      'y': 'CXI:DG2:MMS:08'}},
 'dg2lens': {'desc': 'CXI DG2 Be Focusing Lense Assembly',
             'device': 'lens',
             'pvs': {'x': 'CXI:DG2:MMS:05', 'y': 'CXI:DG2:MMS:06'}},
 'dg2pim': {'desc': 'CXI DG2 pop-in camera',
            'det': {'detId': 0,
                    'detName': 'CxiDg2',
                    'devId': 0,
                    'devName': 'TM6740'},
            'device': 'pim',
            'pvs': {'y': 'CXI:DG2:MMS:10', 'zoom': 'CXI:DG2:CLZ:01'}},
 'dg2slit': {'desc': 'CXI DG2 slits',
             'device': 'slit',
             'pvs': {'xm': 'CXI:DG2:MMS:02',
                     'xp': 'CXI:DG2:MMS:01',
                     'ym': 'CXI:DG2:MMS:04',
                     'yp': 'CXI:DG2:MMS:03'}},
 'dg3spec': {'desc': 'CXI DG3 spectrometer',
             'det': {'detId': 0,
                     'detName': 'CxiDg3',
                     'devId': 0,
                     'devName': 'Opal1000'},
             'device': 'dg3spec',
             'pvs': {'phi': 'CXI:DG3:MMS:12'}},
 'dg4diode': {'desc': 'CXI DG4 diode assembly',
              'det': {'detId': 0,
                      'detName': 'CxiDg4',
                      'devId': 0,
                      'devName': 'Ipimb'},
              'device': 'diode',
              'pvs': {'targ': 'CXI:DG4:MMS:03',
                      'x': 'CXI:DG4:MMS:01',
                      'y': 'CXI:DG4:MMS:02'}},
 'dg4pim': {'desc': 'CXI DG4 pop-in camera assembly',
            'det': {'detId': 0,
                    'detName': 'CxiDg4',
                    'devId': 0,
                    'devName': 'TM6740'},
            'device': 'pim',
            'pvs': {'x': 'CXI:DG4:MMS:04',
                    'y': 'CXI:DG4:MMS:05',
                    'zoom': 'CXI:DG4:CLZ:01'}},
 'dia': {'desc': 'CXI DIA Attenuators in the XRT',
         'device': 'attn',
         'pvs': {'a0': 'XRT:DIA:MMS:02',
                 'a1': 'XRT:DIA:MMS:03',
                 'a2': 'XRT:DIA:MMS:04',
                 'a3': 'XRT:DIA:MMS:11',
                 'a4': 'XRT:DIA:MMS:06',
                 'a5': 'XRT:DIA:MMS:07',
                 'a6': 'XRT:DIA:MMS:08',
                 'a7': 'XRT:DIA:MMS:09',
                 'a8': 'XRT:DIA:MMS:10',
                 'a9': 'XRT:DIA:MMS:05'}},
 'ds1': {'desc': 'CXI DS1 CSpad Detector Stand',
         'det': {'detId': 0,
                 'detName': 'CxiDs1',
                 'devId': 0,
                 'devName': 'Cspad'},
         'device': 'cspad',
         'pvs': {'m1': 'CXI:DS1:MMS:01',
                 'm2': 'CXI:DS1:MMS:02',
                 'm3': 'CXI:DS1:MMS:03',
                 'm4': 'CXI:DS1:MMS:04',
                 'm5': 'CXI:DS1:MMS:05',
                 'z': 'CXI:DS1:MMS:06'}},
 'ds2': {'desc': 'CXI DS2 CSpad Detector Stand',
         'det': {'detId': 0,
                 'detName': 'CxiDs2',
                 'devId': 0,
                 'devName': 'Cspad'},
         'device': 'cspad',
         'pvs': {'m1': 'CXI:DS2:MMS:01',
                 'm2': 'CXI:DS2:MMS:02',
                 'm3': 'CXI:DS2:MMS:03',
                 'm4': 'CXI:DS2:MMS:04',
                 'm5': 'CXI:DS2:MMS:05',
                 'z': 'CXI:DS2:MMS:06'}},
 'dsbslit': {'desc': 'CXI DSB slits',
             'device': 'slit',
             'pvs': {'xm': 'CXI:DSB:MMS:09',
                     'xp': 'CXI:DSB:MMS:08',
                     'ym': 'CXI:DSB:MMS:11',
                     'yp': 'CXI:DSB:MMS:10'}},
 'ebeam': {'desc': 'LCLS ebeam data',
           'det': {'type': 0, 'typeName': 'EBeam'},
           'device': 'ebeam'},
 'gasdet': {'desc': 'LCLS gas detector',
            'det': {'type': 2, 'typeName': 'FEEGasDetEnergy'},
            'device': 'gasdet'},
# 'imp0': {'desc': 'CXI DG2 IMP',
#          'det': {'detId': 0,
#                  'detName': 'CxiEndstation',
#                  'devId': 0,
#                  'devName': 'Imp'},
#          'device': 'imp'},
# 'imp1': {'desc': 'CXI DG3 IMP',
#          'det': {'detId': 0,
#                  'detName': 'CxiEndstation',
#                  'devId': 1,
#                  'devName': 'Imp'},
#          'device': 'imp'},
 'kb1': {'desc': 'CXI KB1 Optics Motion',
         'device': 'kb',
         'pvs': {'hp': 'CXI:KB1:MMS:07',
                 'hr': 'CXI:KB1:MMS:08',
                 'hx': 'CXI:KB1:MMS:05',
                 'hy': 'CXI:KB1:MMS:06',
                 'vp': 'CXI:KB1:MMS:11',
                 'vx': 'CXI:KB1:MMS:09',
                 'vy': 'CXI:KB1:MMS:10'}},
 'kb1slitds': {'desc': 'CXI KB1 downstream slits',
               'device': 'slit',
               'pvs': {'xm': 'CXI:KB1:MMS:14',
                       'xp': 'CXI:KB1:MMS:13',
                       'ym': 'CXI:KB1:MMS:16',
                       'yp': 'CXI:KB1:MMS:15'}},
 'kb1slitus': {'desc': 'CXI KB1 upstream slits',
               'device': 'slit',
               'pvs': {'xm': 'CXI:KB1:MMS:02',
                       'xp': 'CXI:KB1:MMS:01',
                       'ym': 'CXI:KB1:MMS:04',
                       'yp': 'CXI:KB1:MMS:03'}},
 'kb2': {'desc': 'CXI KB2 Optics Motion',
         'device': 'kb',
         'pvs': {'hl': 'CXI:KB2:MMS:03',
                 'hp': 'CXI:KB2:MMS:04',
                 'hr': 'CXI:KB2:MMS:05',
                 'hx': 'CXI:KB2:MMS:01',
                 'hy': 'CXI:KB2:MMS:02',
                 'vp': 'CXI:KB2:MMS:08',
                 'vx': 'CXI:KB2:MMS:06',
                 'vy': 'CXI:KB2:MMS:07'}},
 'opal1k': {'desc': 'CXI Opal1k',
            'det': {'detId': 0,
                    'detName': 'CxiEndstation',
                    'devId': 1,
                    'devName': 'Opal1000'},
            'device': 'opal1k'},
 'opal4k': {'desc': 'CXI Opal4k',
            'det': {'detId': 0,
                    'detName': 'CxiEndstation',
                    'devId': 1,
                    'devName': 'Opal4000'},
            'device': 'opal4k'},
 'pi1': {'desc': 'CXI PI1 Particle Injector Coarse Motion',
         'device': 'xyz',
         'pvs': {'x': 'CXI:PI1:MMS:01',
                 'y': 'CXI:PI1:MMS:02',
                 'z': 'CXI:PI1:MMS:03'}},
 'pi1fine': {'desc': 'CXI PI1 Particle Injector Fine Motion',
             'device': 'xyz',
             'pvs': {'x': 'CXI:USR:MMS:01',
                     'y': 'CXI:USR:MMS:02',
                     'z': 'CXI:USR:MMS:03'}},
 'pi2': {'desc': 'CXI PI2 Particle Injector Coarse Motion',
         'device': 'xyz',
         'pvs': {'x': 'CXI:PI2:MMS:01',
                 'y': 'CXI:PI2:MMS:02',
                 'z': 'CXI:PI2:MMS:03'}},
 'pi2fine': {'desc': 'CXI PI2 Particle Injector Fine Motion',
             'device': 'xyz',
             'pvs': {'x': 'CXI:USR:MMS:09',
                     'y': 'CXI:USR:MMS:10',
                     'z': 'CXI:USR:MMS:11'}},
 'picker': {'desc': 'CXI Pulse Picker at DSB',
            'device': 'picker',
            'pvs': {'pp': 'CXI:ATC:MMS:29',
                    'x': 'CXI:ATC:MMS:28',
                    'y': 'CXI:ATC:MMS:27'}},
 'sample': {'desc': 'CXI Sample Stack in SC1',
            'device': 'xyz',
            'pvs': {'x': 'CXI:SC1:MMS:02',
                    'y': 'CXI:SC1:MMS:03',
                    'z': 'CXI:SC1:MMS:04'}},
 'sc1led': {'desc': 'CXI Sample Stack in SC1',
            'device': 'stick',
            'pvs': {'stick': 'CXI:SC1:MMS:05'}},
 'sc1questar': {'desc': 'SC1 questar microscope',
                'det': {'detId': 0,
                        'detName': 'CxiEndstation',
                        'devId': 1,
                        'devName': 'Opal2000'},
                'device': 'questar',
                'pvs': {'x': 'CXI:USR:MMS:17',
                        'y': 'CXI:USR:MMS:18',
                        'z': 'CXI:SC1:MMS:01'}},
 'timetool': {'desc': 'CXI Time Tool',
              'det': {'detId': 0,
                      'detName': 'CxiDsu',
                      'devId': 0,
                      'devName': 'Opal1000'},
              'device': 'timetool'}}
